# Generated by Django 5.2.15 on 2026-07-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
