# Generated by Django 5.2.15 on 2026-07-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_patient_deactivated_at_patient_inactive_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
