# Generated by Django 5.2.15 on 2026-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
