# Generated by Django 5.2.15 on 2026-07-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_specialist_deactivated_at_specialist_inactive_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
