# Generated by Django 5.2.15 on 2026-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_status',
            field=models.CharField(choices=[('Draft', 'Borrador'), ('Sent', 'Enviado'), ('Accepted', 'Aceptado'), ('Rejected', 'Rechazado'), ('Completed', 'Completado')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Efectivo'), ('Card', 'Tarjeta'), ('Transfer', 'Transferencia'), ('Insurance', 'Seguro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestedtreatment',
            name='treatment_status',
            field=models.CharField(choices=[('Suggested', 'Sugerido'), ('Budgeted', 'Presupuestado'), ('In Progress', 'En tratamiento'), ('Finished', 'Finalizado'), ('Cancelled', 'Cancelado')], default='Suggested', max_length=30),
        ),
    ]
