# Generated by Django 5.2.15 on 2026-07-12 03:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_budget_budget_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetdetail',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetdetail',
            name='procedure',
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-issue_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['patient__last_name', 'patient__first_name']},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='suggestedtreatment',
            options={'ordering': ['-diagnosis_date', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_specialist_appointment',
        ),
        migrations.RemoveField(
            model_name='suggestedtreatment',
            name='treatment_description',
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestedtreatment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedtreatment',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedtreatment',
            name='clinical_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedtreatment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suggestedtreatment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestedtreatment',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.procedure'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Pending', 'Pendiente'), ('Attended', 'Atendida'), ('Cancelled', 'Cancelada'), ('No Show', 'No asistió')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.specialist'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='budget',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='suggested_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='clinic.suggestedtreatment'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener exactamente 8 dígitos.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 9 dígitos.', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clinic.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clinic.budget'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='license_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'El número de colegiatura debe tener al menos 5 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 9 dígitos.', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialists', to='clinic.specialty'),
        ),
        migrations.AlterField(
            model_name='suggestedtreatment',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_treatments', to='clinic.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='suggestedtreatment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_treatments', to='clinic.specialist'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['suggested_treatment'], name='clinic_budg_suggest_d50398_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_status'], name='clinic_budg_budget__ff1831_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['appointment'], name='clinic_paym_appoint_7d7ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='clinic_paym_payment_a8b62b_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedtreatment',
            index=models.Index(fields=['procedure'], name='clinic_sugg_procedu_de8640_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedtreatment',
            index=models.Index(fields=['specialist'], name='clinic_sugg_special_14600e_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedtreatment',
            index=models.Index(fields=['treatment_status'], name='clinic_sugg_treatme_d38252_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('specialist', 'appointment_date', 'appointment_time'), name='unique_active_specialist_appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('patient', 'appointment_date', 'appointment_time'), name='unique_active_patient_appointment'),
        ),
        migrations.DeleteModel(
            name='BudgetDetail',
        ),
    ]
